# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='state',
            field=models.IntegerField(choices=[(0, 'offline'), (1, 'online')], db_index=True, default=0),
        ),
    ]
