# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 03:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb_api', '0002_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networkdevice',
            old_name='machine_type',
            new_name='vendor',
        ),
    ]
