# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb_api', '0003_auto_20170326_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='usergroup',
        ),
        migrations.AddField(
            model_name='user',
            name='usergroup',
            field=models.ManyToManyField(null=True, to='cmdb_api.UserGroup'),
        ),
    ]
