# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb_api', '0004_auto_20170329_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='name',
            field=models.CharField(default='aa', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
