# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb_api', '0005_auto_20170330_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetgroup',
            old_name='agname',
            new_name='asstgroup',
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='assetgroup',
            field=models.ManyToManyField(blank=True, null=True, to='cmdb_api.AssetGroup'),
        ),
    ]
