# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb_api', '0006_auto_20170330_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='auth',
            name='key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='auth',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='idc',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
