# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb_api', '0007_auto_20170330_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetgroup',
            old_name='asstgroup',
            new_name='groupname',
        ),
    ]
